### ISSUE TITLE
stackTrace segfaults when used with OpenMP in clang10 debug on Quartz

### ISSUE THREAD

**Issue by corbett5** [GEOSX/LvArray#179]
The call to `backtrace` in `stackTrace` fails if used after an OpenMP parallel region but only with clang10 debug on Quartz. Strange.

**Comment by corbett5** [comment]
Checkout https://github.com/boostorg/stacktrace, they seem to get line numbers too which would be awesome.

**Comment by rrsettgast** [comment]
That sounds like a win.
