### ISSUE TITLE
GCC 9.2.1 issue with static_assert

### ISSUE THREAD

**Issue by corbett5** [GEOSX/LvArray#214]
Henri Calandra had issues compiling GEOSX with GCC 9.2.1. The problem were asserts of the form `static_assert( !typeManipulation ::always_true<T>, … )`. The issue appears to be in the implementation of `always_true` whose purpose is to obfuscate the conditional so that the `static_assert` is only triggered if the function is used, not when it's parsed. It appears that the current implementation is too simple.

**Comment by cssherman** [comment]
@corbett5 - I was trying to install the code on a machine with gcc 9.3.0 this morning actually, and ran into the same issue.  I'd be happy to help with testing a potential solution!

**Comment by klevzoff** [comment]
Some observations:
 * No errors with ether gcc-8.4 or gcc-10.2 (but I do also get this error with 9.3.0)
 * Replacing `typeManipulation ::always_true<T>` with another dependent trivial condition like `std::is_same<T,T>::value` does not help, the static_assert is still being triggered
 * Replacing `static_assert`s with a runtime failure (`exit(1)`), allows building the code and passing all unit tests that had compilation errors (e.g. `testArrayView_toViewConst`). Meaning those functions are indeed not being called, the compiler just decides to instantiate it for no reason.

**Comment by corbett5** [comment]
Actually via the magic of spack I was able to install GCC 9.3.0 locally, I'll come up with a fix.

**Comment by corbett5** [comment]
It appears that the issue is that with GCC 9 `std::declval< T >().foo()` will call the rvalue overload of `T::foo` if it exists where as every other compiler I've tried (including GCC 8 and 10) call the lvalue overload. Seems like it's probably a compiler bug but the fix is to just change to `std::declval< T & >().foo()`.

**Comment by corbett5** [comment]
@klevzoff @cssherman if either of you have a set of GEOSX TPLs built with GCC 9 would you mind giving https://github.com/GEOSX/GEOSX/pull/1237 a try? I was able to build LvArray so there shouldn't be any issues.

**Comment by cssherman** [comment]
@corbett5 - It seems like this has fixed that error on my end for gcc 9.3.0.  

I did run into an un-related issue with linking openmpi on the machine I'm testing, which I'm working to resolve.  So, I can't quite guarantee that the build works though.

**Comment by corbett5** [comment]
Awesome, thanks @cssherman!
