### ISSUE TITLE
remove reinterpret_cast from Array classes

### ISSUE THREAD

**Issue by rrsettgast** [GEOSX/LvArray#45]
In the conversion to const user defined conversions we have code like this:
```
  operator Array<T const, NDIM, INDEX_TYPE> const & () const
  {
    return reinterpret_cast<Array<T const, NDIM, INDEX_TYPE> const &>(*this);
  }
```

While this is great from the brevity point of view, it may result in undefined behavior. We should keep this in mind, and perhaps at some point consider just shallow constructing new objects for as part of this type of user defined conversion.

**Comment by corbett5** [comment]
Done except for `Array< Array< T > >` which isn't really possible.
